# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "opened", "synchronize", "edited" ]

permissions:
  contents: read

jobs:
  test:
    name: 'Build and Test Library'
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        arch: [x86_64, arm64]
        dc: [ldc-beta, dmd-master, ldc-1.30.0]
        exclude:
          - { dc: dmd-master, arch: arm64 }

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build with ${{ matrix.os }} ${{ matrix.dc }} (${{ matrix.build }})' 
      run: |
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        dub test --config=unittest

        # Ditto, in release mode.
        # Sometimes D packages break in release mode, so this is important to test.
        dub test --config=unittest --build=release